Repository QuantEcon/lecture-source-jl, pull requests merged in 2018-09, with the labels that each got.

#53 Undeprecate Uncertainty Traps
  rst_files/_static/code/uncertainty_traps/uncertainty_traps.jl
  rst_files/uncertainty_traps.rst
Labels: undeprecate

#46 Test Orthogonal Projections
  rst_files/orth_proj.rst
Labels: enhancement

#48 Test Linear Models
  rst_files/linear_models.rst
Labels: enhancement

#49 Test Finite Markov
  rst_files/finite_markov.rst
Labels: enhancement

#50 Test Stationary Densities
  rst_files/stationary_densities.rst
Labels: enhancement

#51 Test Kalman
  rst_files/kalman.rst
Labels: enhancement

#55 Test McCall I
  rst_files/mccall_model.rst
Labels: enhancement

#56 Test McCall II
  rst_files/mccall_model_with_separation.rst
Labels: enhancement

#59 Update McMcall II
  rst_files/mccall_model_with_separation.rst
Labels: undeprecate

#57 Test Wald-Friedman
  rst_files/wald_friedman.rst
Labels: enhancement

#58 WIP: Update mccall
  rst_files/mccall_model.rst
Labels: undeprecate

#60 Update Wald Friedman
  rst_files/wald_friedman.rst
Labels: undeprecate

#61 Test and Undeprecate McCall III
  rst_files/odu.rst
Labels: enhancement, undeprecate

#64 Test and Undeprecate On-the-Job-Search (McCall V)
  rst_files/jv.rst
Labels: enhancement, undeprecate

#66 Test and Undeprecate "Optimal Growth II: Time Iteration"
  rst_files/coleman_policy_iter.rst
Labels: enhancement, undeprecate

#69 Test and Undeprecate "LQ Dynamic Programming Problems"
  rst_files/lqcontrol.rst
Labels: enhancement, undeprecate

#71 Test and Undeprecate "Optimal Savings I: The Permanent Income Model"
  rst_files/perm_income.rst
Labels: enhancement, undeprecate

#63 Test and Undeprecate McCall IV
  rst_files/_static/figures/career_solutions_ex3_jl.png
  rst_files/career.rst
Labels: enhancement, undeprecate

#65 Test and Undeprecate "Optimal Growth I: The Optimal Stochastic Growth Model"
  rst_files/optgrowth.rst
Labels: enhancement, undeprecate

#75 Test and Undeprecate "Optimal Savings III: Occasionally Binding Constraints"
  rst_files/ifp.rst
Labels: enhancement, undeprecate

#77 Update and Test Robustness
  rst_files/robustness.rst
Labels: undeprecate

#78 Update and Test Schelling
  rst_files/schelling.rst
Labels: undeprecate

#79 Update Lake Model
  rst_files/_static/code/mccall/compute_reservation_wage.jl
  rst_files/_static/code/mccall/mccall_bellman_iteration.jl
  rst_files/lake_model.rst
  rst_files/mccall_model_with_separation.rst
Labels: undeprecate

#80 Update and Test Rational Expectations
  rst_files/rational_expectations.rst
Labels: undeprecate

#83 Test and Undeprecate "The Aiyagari Model"
  rst_files/aiyagari.rst
Labels: enhancement, undeprecate

#94 Update LQRamsey
  rst_files/lqramsey.rst
Labels: undeprecate

#96 Update Tax Recur
  rst_files/opt_tax_recur.rst
Labels: undeprecate

#93 Update Dyn Stack
  rst_files/dyn_stack.rst
Labels: undeprecate

#92 Update Classical Filtering
  rst_files/_static/code/lu_tricks/control_and_filter.jl
  rst_files/classical_filtering.rst
Labels: undeprecate

#90 Update Multiplicative Functionals
  rst_files/multiplicative_functionals.rst
Labels: undeprecate

#89 Update Additive Functionals
  rst_files/additive_functionals.rst
Labels: undeprecate

#88 Update Estimation of Spectra
  rst_files/estspec.rst
Labels: undeprecate

#87 Update ARMA
  rst_files/arma.rst
Labels: undeprecate

#86 Update Globalization and Cycles
  rst_files/matsuyama.rst
Labels: undeprecate

#85 Update and Test Default Risk and Income Fluctuations
  rst_files/arellano.rst
Labels: undeprecate

#81 Update and Tests Markov Perf
  rst_files/markov_perf.rst
  rst_files/uncertainty_traps.rst
Labels: WIP, undeprecate

#72 Test and Undeprecate "Optimal Savings II: LQ Techniques"
  rst_files/perm_income_cons.rst
Labels: enhancement, undeprecate

#105 Test "Markov Perfect Equilibrium"
  rst_files/markov_perf.rst
Labels: enhancement

#106 Test "Asset Pricing I: Finite State Models"
  rst_files/markov_asset.rst
Labels: enhancement

#107 Test "Asset Pricing II: The Lucas Asset Pricing Model"
  rst_files/lucas_model.rst
Labels: enhancement

#109 Test "Default Risk and Income Fluctuations"
  rst_files/arellano.rst
Labels: enhancement

#110 Test "Globalization and Cycles"
  rst_files/matsuyama.rst
Labels: enhancement

#111 Test "Estimation of Spectra"
  rst_files/estspec.rst
Labels: enhancement

#112 Test "Additive Functionals"
  rst_files/additive_functionals.rst
Labels: enhancement

#115 Test "Classical Filtering With Linear Algebra"
  rst_files/_static/code/lu_tricks/control_and_filter.jl
  rst_files/classical_filtering.rst
Labels: enhancement

#116 Test "Dynamic Stackelberg Problems"
  rst_files/dyn_stack.rst
Labels: enhancement

#117 Test "Optimal Taxation in an LQ Economy"
  rst_files/lqramsey.rst
Labels: enhancement

#118 Test "Optimal Taxation with State-Contingent Debt"
  rst_files/opt_tax_recur.rst
Labels: enhancement
